### ISSUE TITLE
Adding a License Text 

### ISSUE THREAD

**Issue by bluzeey** [bluzeey/frontendeval-solutions#1]
The current repository doesn't include a License.txt file. Create a MIT License file for the repository. Add up my name for copyrights. Here's an idea of what you are supposed to do:
https://github.com/bluzeey/netflix-clone/blob/main/LICENSE.txt.
Also add up a MIT License shield button in Readme.md at the top which links to the same License file

**Comment by lorenzovngl** [comment]
I could do it if you want.

**Comment by bluzeey** [comment]
Yeah sure , go ahead. You need to edit two files for the same Readme.md for the button at the top. And a new file for the license . Good luck!

**Comment by bluzeey** [comment]
Thanks Lorenzovngl, I am closing the issue. But feel free to check up on the repository to do more beginner friendly issue, if you would like .
