### ISSUE TITLE
Setting up the input and function which takes word  and 6 inputs

### ISSUE THREAD

**Issue by bluzeey** [bluzeey/frontendeval-solutions#2]
I have set up the basic files in Word guessing game folder. Try to create a input with a function in javascript which only takes up value and submits it. Have a variable in javascript file which is set to 6 and is reduced everytime onClick.

**Comment by a-tanvi** [comment]
Hey! Can i take on this issue?

**Comment by bluzeey** [comment]
Oh , yeah sure ! But I had copied some initial files for the challenge, you might need to make your own initial template or you can edit out the existing files . But then it would not be very beginner friendly. Here's some more details about what you would require to do. https://frontendeval.com/questions/word-game .
